# Specifies the runtime environment
runtime: python37 

# Specifies the instance class (Select it based on expected traffic)
instance_class: F2

# The Entry point for the application
entrypoint: python app.py
